"""Test of jac importing python."""
# import:py openai;
import:py pyfunc;
# import:py random;
# import:py from pyfunc, my_print;
# import:py torch;
# import:y tensor;

with entry {
    # print('pyfunc f: ',pyfunc);
    # print(torch.rand(5, 3));
    # print(tensor.rand(5, 3));
    # print(pyfunc.hello_world_bytes);
    # print(pyfunc.path);
    # print(type(pyfunc.path));
    # print(type(pyfunc.hello_world_bytes));
    # print(pyfunc.ShapeType.CIRCLE);
    # print(pyfunc.MyClass2().my_method());
    # my_print(pyfunc);
    # print(random.random());
}

# import:py circle_pysolo;
# import:py from circle_pysolo, calculate_area;

# with entry {
#     print(f"are {calculate_area(2.0)}");
# }
