"""Test of jac importing python."""
import:py os;
import:py pyfunc;
# import:py random;
# import:py from pyfunc, my_print;

with entry {
    print(pyfunc.f);
    # print(pyfunc.hello_world_bytes);
    # print(pyfunc.path);
    # print(type(pyfunc.path));
    # print(type(pyfunc.hello_world_bytes));
    # print(pyfunc.ShapeType.CIRCLE);
    # print(pyfunc.MyClass2().my_method());
    # my_print(pyfunc);
    # print(random.random());
}

# import:py circle_pysolo;
# import:py from circle_pysolo, calculate_area;

# with entry {
#     print(f"are {calculate_area(2.0)}");
# }
