site_name: The Jac Programming Language
site_url: https://jac-lang.org
nav:
    - ~$: 'index.md'
    - ~/start$:
      - 'start.md'
      - 'start/installation.md'
      - 'start/jac_in_a_flash.md'
    - ~/learn$:
      - ~/for_coders:
        - 'learn/guide.md'
        - 'learn/jac_ref.md'
        - 'learn/with_llm.md'
        - 'learn/tips_tricks.md'
        - 'learn/jac_plugins.md'
      - ~/for_contributors:
        - 'learn/contrib.md'
      - ~/w.i.p$:
        - 'learn/ast_doc.md'
        - ~/projects$:
          - 'projects/auto_ref.md'

    - ~/why$: 'why.md'
    # - ~/roadmap$: 'roadmap.md'
    - ~/github$: https://github.com/Jaseci-Labs/jaclang

theme:
    logo: 'assets/logo.png'
    name: 'material'
    palette:
        scheme: 'slate'
        primary: 'black'
        accent: 'orange'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      pygments_style: 'autumn'
  - pymdownx.inlinehilite
  # - codehilite:
  #     linenums: true
  - pymdownx.snippets:
      base_path: ['.', '../../']
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
copyright: Copyright &copy; 2023 - 20XX Jac Hackers Everwhere

plugins:
  - search
  - open-in-new-tab
