name: PyPI Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install Build Tool
        run: |
          python3 -m pip install --upgrade pip
          pip install -U setuptools wheel twine build
      - name: Build and publish package
        run: |
          python3 -m build
          python3 -m twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      - run: pip install githubrelease
      - run: python scripts/gh_release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}